apiVersion: apps/v1
kind: Deployment
metadata:
  name: paystream
spec:
  replicas: 3
  selector:
    matchLabels:
      app: paystream
  template:
    metadata:
      labels:
        app: paystream
    spec:
      containers:
      - name: paystream
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: '64Mi'
            cpu: '250m'
          limits:
            memory: '128Mi'
            cpu: '500m'
